[tool.poetry]
name = "coursework-5"
version = "0.1.0"
description = ""
authors = ["Slava Lukin <bafana.slv@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
